[package]
name = "vertex_layout_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
vertex_traits = { path = "../vertex_traits" }
syn = "1.0"
quote = "1.0"
mem_macros = "1.0"
wgpu = "0.9"